name: Generate Documentation Preview

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Generate Previews"]
    types:
      - completed
    paths:
      - '.github/workflows/generate-documentation.yml'
      - 'docs/users/**'
      - 'scripts/docs.js'
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'typedoc.json'

jobs:
  doc_preview:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish preview
        id: publish_preview
        uses: afc163/surge-preview@v1
        env:
          # https://playwright.dev/docs/installation/#skip-browser-downloads
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: build/docs
          failOnError: true
          teardown: 'true'
          build: |
            npm ci
            npm run docs

