name: Generate Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'docs/users/**'
      - 'scripts/docs.js'
      - '.github/workflows/generate-documentation.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'docs/users/**'
      - 'scripts/docs.js'
      - '.github/workflows/generate-documentation.yml'

jobs:
  generate_doc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm ci
      - name: Build docs
        run: npm run user-docs
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: documentation-${{github.sha}}
          path: build/docs

  push_to_gh_pages:
    # only when 'on push to master'
    if: github.event_name == 'push' &&  github.event.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    needs: generate_doc
    steps:
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: documentation-${{github.sha}}
      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          keep_files: true
          user_name: 'process-analytics-bot'
          user_email: '62586190+process-analytics-bot@users.noreply.github.com'
