name: Generate Documentation

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - '.github/workflows/generate-documentation.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'docs/**'
      - '.github/workflows/generate-documentation.yml'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./docs/build-doc.bash
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: documentation
          path: build/docs

  push-to-gh-pages:
    # only when 'on push to master'
    if: github.event_name == 'push' &&  github.event.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Download
        uses: actions/download-artifact@v1
        with:
          name: documentation
      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation
          keep_files: true
          user_name: 'process-analytics-bot'
          user_email: '62586190+process-analytics-bot@users.noreply.github.com'
