name: Upload Demo Archive

on:
  push:
    branches:
      - master
    tags:
      -  v*
    paths-ignore:
      - '.github/workflows/build.yml'
      - '.github/workflows/codeql-analysis.yml'
      - '.github/workflows/fill-gh-draft-release.yml'
      - '.github/workflows/generate-documentation.yml'
      - '.github/workflows/generate-documentation-api.yml'
      - '.github/workflows/release.yml'
      - '.gitignore'
      - 'docs/**'
      - '*.md'
      - LICENSE
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/build.yml'
      - '.github/workflows/codeql-analysis.yml'
      - '.github/workflows/fill-gh-draft-release.yml'
      - '.github/workflows/generate-documentation.yml'
      - '.github/workflows/generate-documentation-api.yml'
      - '.github/workflows/release.yml'
      - '.gitignore'
      - 'docs/**'
      - '*.md'
      - LICENSE

jobs:
  upload_demo_archive:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Setup GitHub cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-demo-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-demo-
      - name: Install dependencies
        run: npm ci
      - name: Build Demo
        run: npm run demo
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: demo-${{github.sha}}
          path: build/demo

