name: Upload Demo Archive & Trigger Examples Repository Update

on:
  push:
    tags:
      -  v*
    paths-ignore:
      - '.github/workflows/build.yml'
      - '.github/workflows/codeql-analysis.yml'
      - '.github/workflows/fill-gh-draft-release.yml'
      - '.github/workflows/generate-documentation.yml'
      - '.github/workflows/generate-documentation-api.yml'
      - '.github/workflows/release.yml'
      - '.gitignore'
      - 'docs/**'
      - '*.md'
      - LICENSE

jobs:
  upload_demo_archive:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Setup GitHub cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Build Demo
        run: npm run demo
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: demo-${{github.sha}}
          path: build/demo
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v*}
      - name: Send Repository Dispatch event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_RELEASE_TOKEN }}
          repository: process-analytics/bpmn-visualization-examples
          event-type: update_bpmn_visualization_version
          client-payload: '{
              "build_demo_repo": "${{ github.repository }}",
              "build_demo_workflow_id": "upload-demo-archive.yml",
              "artifact_name": "demo-${{github.sha}}",
              "version": "${{ steps.get_version.outputs.VERSION }}"
            }'
